### ISSUE TITLE
You must set `limit: nil` to have unlimited retries

### ISSUE THREAD

**Issue by phlegx** [gocardless/activejob-retry#35]
Hi! I use Sidekiq version 4.x and if I set:

```ruby
constant_retry unlimited_retries: true, delay: 10.seconds
```

in my ActiveJob I get this error ```You must set `limit: nil` to have unlimited retries```! If I set ```unlimited_retries: true``` limit should be set to nil automatically in the background.

**Comment by isaacseymour** [comment]
This is on purpose - unlimited retries is a dangerous option, so it's intentionally hard to switch on

**Comment by phlegx** [comment]
OK, thx.
